Rails 4 Upgrade Issue: Downgrade to Rails 3 Session Cookies blow as data structure changes in Rails 4 to Hash and blows when fire sweep method NoMethodError: undefined method 'sweep' for Hash